---
version: '3.2'
services:
  go:
    image: bazel/cmd/go:go_container
    command:
      - -redirects-file=/var/redirects.json
    ports:
      - 80:8080
    volumes:
      - type: bind
        source: ./var
        target: /var
